### ISSUE TITLE
Dagger Missing Binding error on latest download.

### ISSUE THREAD

**Issue by dishhead** [salamquran/SalamQuran-android#2]
I am getting the following error upon compilation:
A:\PRJ\AQMY3\app\src\main\java\com\ermile\salamquran\android\component\application\ApplicationComponent.java:41: error: [Dagger/MissingBinding] java.util.Map<java.lang.String,com.ermile.data.source.PageProvider> cannot be provided without an @Provides-annotated method.
public interface ApplicationComponent {
       ^
      java.util.Map<java.lang.String,com.ermile.data.source.PageProvider> is injected at
          com.ermile.salamquran.android.ui.fragment.QuranSettingsFragment.pageTypes
      com.ermile.salamquran.android.ui.fragment.QuranSettingsFragment is injected at
          com.ermile.salamquran.android.component.application.ApplicationComponent.inject(com.ermile.salamquran.android.ui.fragment.QuranSettingsFragment)
  It is also requested at:
      com.ermile.salamquran.android.data.QuranDataModule.provideQuranPageProvider(providers, …)
      com.ermile.salamquran.android.pageselect.PageSelectPresenter(…, pageTypes)
  The following other entry points also depend on it:
      com.ermile.salamquran.android.component.application.ApplicationComponent.inject(com.ermile.salamquran.android.data.QuranDataProvider)
      com.ermile.salamquran.android.component.application.ApplicationComponent.inject(com.ermile.salamquran.android.service.AudioService)
      com.ermile.salamquran.android.component.application.ApplicationComponent.inject(com.ermile.salamquran.android.service.QuranDownloadService)

**Comment by dishhead** [comment]
I left all the gradle untouched, except:

    implementation 'ru.tinkoff.recyclerviewpager:recyclerviewpager:1.0.10'
    //implementation 'com.github.lsjwzh.RecyclerViewPager:lib:v1.1.2'

as the later is not available.

Also,
import com.ermile.salamquran.android.module.fragment.QuranPageModule;

and not in data directory.

**Comment by amingoli78** [comment]
Hi dear friend
These are previous developer bugs

Please submit a bug report with the link below:
[issue Again](https://github.com/quran/quran_android/issues/new)
